### ISSUE TITLE
[feature request] preview your placement

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#1]
Each of the tiny redstone components should show a preview of where you will place it. (transparent ghost block)

Already on your to-do list, similar (highlight the grid)

**Comment by dannydjdk** [comment]
I do like this idea, though I am likely to implement a simple "grid" or something similar first, just because I'll be able to complete that sooner.

**Comment by lublak** [comment]
Actually, that would also be perfectly sufficient.

**Comment by dannydjdk** [comment]
So, I wasn't necessarily planning on doing a full placement preview right now, but as I started mapping out my approach to the grid highlighting idea, I decided to just look into what the preview would require. Once that idea started swimming around in my head, I really wanted to make it happen. So, here it is! I hope to get a release out tonight.

**Comment by dannydjdk** [comment]
Released

**Comment by lublak** [comment]
I love it! 
![grafik](https://user-images.githubusercontent.com/44057030/111868840-87123700-897c-11eb-9f77-4458acc207cf.png)
Now building has become 1000 per cent easier.
