### ISSUE TITLE
[Bug] server dies when CC gets items from RS with items from this mod are inside

### ISSUE THREAD

**Issue by Hiranus** [dannydjdk/Tiny-Redstone#100]
When I try to get list of items in my main RS network with the use of CC:Tweaked and Advanced Peripherals server dies. If I remove Tiny Redstone items from RS then I can get this item list (almost 6000 items in it). I tried to reproduce it in single player but for some reason I couldn't, but it happens every time I try when its on my server.
I am playing modified AllTheMods 6 (MC 1.16.5) 

https://pastebin.com/210iib01

**Comment by dannydjdk** [comment]
Thanks for the report! There's nothing particularly special about Tiny Redstone items other than the large amount of NBT data for assembled circuits, custom rendering and custom tooltips. But, there are many mods that do similar things.

Have you been able to notice which items cause problems? If not, are you able to do a bit of testing to help narrow this down? If so, please add the following items to your system in the following order. Wait for a little while between each set of items and see at which point does the system breaks:
- Simple Tiny Redstone items that do not have custom tooltips, like the wrench or silicon.
- Simple circuit components with tooltips, like tiny redstone dust
- Empty blueprint
- Blueprint with saved circuit (these a lot of NBT data)
- Redstone Panel with no circuitry (custom rendering)
- Redstone Panels with circuitry (custom rendering and lots of NBT)
- Tiny blocks or circuit covers (these have custom renderings based on block texture used)

**Comment by dannydjdk** [comment]
Oh wait! I see that you have an older version of Tiny Redstone. This is likely related to #97 which has already been fixed.
Please update to the latest version: 1.16.5-1.13.3 and let me know if this fixes the issue for you.

**Comment by Hiranus** [comment]
Sorry for late reply. Yeah, it seems like this is related, as block that was problematic one was tiny wool. I will update and check.

**Comment by Hiranus** [comment]
That was it. I'm closing this ticket. Thanks.
