### ISSUE TITLE
Signal stops when joining world

### ISSUE THREAD

**Issue by HoodBlah** [dannydjdk/Tiny-Redstone#103]
I am using tiny redstone blocks to power a couple blocks. However, when I leave the world and come back, the blocks do not get powered. I need to break the tiny redstone and replace it in order for it to power again.

I place them in the world, without a circuit. I also have the same issue when doing it with the tiny lever as well.

It isn't really a big deal. It's just very annoying having to go back and replace the blocks every time I log in.

If this is a feature, then can you add a config for it please?

Thank you for your mod and time!

**Comment by dannydjdk** [comment]
Thanks for the report. This is definitely not a feature, and not anything I've personally experienced in my extensive gameplay with this mod. Can you let me know the version you're using, modpack if there is one and any other details that might help me try to reproduce this? Screenshots might be helpful too.
Thanks!

**Comment by HoodBlah** [comment]
I am using  (Forge 40.1.51) and (Tiny Redstone 1.18.2-3.2.1)
The modpack I am using is a custom one with 214 mods.

Currently I use the [Advanced Chimney Mod](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys) to bring smoke out of my furnaces and campfire. I use the redstone blocks to power the vents.

When I first log in, the room is filled with smoke.
![626EDAD7-AB04-4275-B71F-ACA7480A8BA5](https://user-images.githubusercontent.com/89415523/176569095-14283144-a04d-4532-8c32-7771956d88eb.jpeg)

A need to go outside the replace the red stone blocks.
[The video is to big](https://photos.app.goo.gl/85JQPE8zCF8YXK4w9)

Then the vent starts to work and the smoke is gone.
![19965B14-9254-476D-BE83-7B70EC4F450F](https://user-images.githubusercontent.com/89415523/176569255-3468ab52-270e-49e1-8e3f-2bc9e7283fcc.jpeg)

Although I tested this mainly with the chimneys, I see this problem only when using the tiny redstone blocks. I also have another chimney powered by a lever, and it works fine.
![4EE16EDC-24D5-414B-AA78-5E637A2DB66F](https://user-images.githubusercontent.com/89415523/176570506-38a0f5d2-0a8e-40fe-a26b-5e736ba0e459.jpeg)

Here is a curseforge launcher profile for the mod pack.
[ForgedGetup.zip](https://github.com/dannydjdk/Tiny-Redstone/files/9015488/ForgedGetup.zip)
Although you could probably test it using only the chimney and tiny redstone mods.

To reproduce:
1. Place a campfire with a vent next to or on top of the campfire.
2. Place a pump next to the vent and power it using the tiny redstone blocks. You may need to place a separate block next to the pump so you can place the tiny redstone block.
3. Leave the world and come back in.

**Comment by dannydjdk** [comment]
Fixed in latest versions for all supported Minecraft versions (1.16.5, 1.18.2, 1.19.2, 1.19.3).
Will be available as soon as Curseforge finishes processing.
