### ISSUE TITLE
Super Repeater GUI Scaling

### ISSUE THREAD

**Issue by Racso201** [dannydjdk/Tiny-Redstone#106]
Firstly, what a fantastic mod!

When increasing the Super Repeater max delay time to 10 minutes (6000 ticks)

The Super Repeater GUI only lets you increase or decrease by 10 ticks. This means you have to click the button 600 times for reach the new maximum.

The config file says that large numbers require more memory, but is 6000 considered large? If this is not considered large then this is a somewhat intended value to set in the config file and therefore I think the mod should have better QoL for setting the delay time.

Could a option be added to either type in the desired tick delay in the Super Repeater GUI or another larger add/subtract buttons alongside the current 10 tick ones.

--

If 6000 ticks is not intended behaviour for the super repeater, then could another component be added that is a super super repeater that allows longer delay times natively? The reason I would like this feature is that currently I have to use a create mod repeater (that can go to 30 minutes) as a input for the Tiny Redstone circuit, but this means the circuit now uses 2 Minecraft blocks, which seems to go against the philosophy of tiny redstone.

Thanks.

**Comment by dannydjdk** [comment]
Thanks for the suggestion! I agree that there should be a faster way to either enter or maybe scroll through this.

Also, it's no longer the case that large numbers have any real impact on memory usage. The tiny redstone repeaters used to be queue-based, but they are now state-based similar to vanilla repeaters. So, I may rethink the defaults for this and possibly allow setting by seconds or even minutes rather than just ticks.

**Comment by dannydjdk** [comment]
Added "documentation" label to update the config file comment to remove the reference to memory usage.

**Comment by dannydjdk** [comment]
Deployed with 1.19-4.1.0.
Will backport to 1.18.2 and 1.16.5

**Comment by Racso201** [comment]
Awesome, thank you!

I will eagerly await a 1.18.2 release as I'm still on that version due to Create. :)

**Comment by dannydjdk** [comment]
Back ports complete and released. (finally)
