### ISSUE TITLE
Vanilla and tiny tick speed is different

### ISSUE THREAD

**Issue by LGN-Ytt** [dannydjdk/Tiny-Redstone#111]
I been working with analog to pulse converters and I made a tiny version of one to use in a data pod. What I found is what number I put in, it gave a 3 or 4 strength increase even though I did the circuit right.

**Comment by dannydjdk** [comment]
Thanks for the report. Can you provide a screenshot or two showing the vanilla setup and the tiny redstone setup, so I can try to replicate the problem? If not, I'll need a detailed description of the circuit. Also, what version are you using?

**Comment by dannydjdk** [comment]
I'm closing this issue for now, since I can not reproduce it without further information. If you are able to provide more details, I can re-open this.
