### ISSUE TITLE
Redstone signal slows down or increases without obvious reason

### ISSUE THREAD

**Issue by Legolas117** [dannydjdk/Tiny-Redstone#112]
I've made a circuit with three panels made of repeaters and note blocks and it's very obvious that at some point the signal slows down in speed to then catch up to then slow down...

This issue has happened to me when building the circuit on the ground too.

My version of minecraft is 1.18.2 with these mods:

![imagen_2022-10-23_214755896](https://user-images.githubusercontent.com/49958232/197414737-9e8ee337-f344-4d98-9c53-b8e5efe6c6a1.png)

The circuit:

![2022-10-23_21 39 10](https://user-images.githubusercontent.com/49958232/197414633-9e656d73-9c77-4929-92ec-d6ddeca2bd58.png)

**Comment by dannydjdk** [comment]
Thanks for the report! However, this is not likely an issue with the mod. Tiny Redstone just taps into Minecraft's tick events. Unfortunately, any lag issues in the game will be reflected in the mod's behavior. You would likely get similar behavior with vanilla redstone. I will test this specific circuit when I get a chance though, just to make sure something unexpected isn't happening.
In the meantime, if you could run the "/forge tps" command while it's happening and let me know the result, that would be helpful. Also, are you running on a local client or a server?

**Comment by dannydjdk** [comment]
Should be fixed with the latest Tiny Redstone versions for Minecraft 1.16.5, 1.18.2, 1.19.2 and 1.19.3.

If it turns out, you were experiencing something else, we can reopen this.
