### ISSUE TITLE
[bug] output not changed if torch gets removed

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#12]
I found a small bug.
If you remove the torch the output not gets an update. (but when building) (a rather "doesn't really matter" bug)
![grafik](https://user-images.githubusercontent.com/44057030/111869478-1240fc00-8980-11eb-8ac4-7f0b6c853ed9.png)

**Comment by dannydjdk** [comment]
So, if you remove the torch in the screenshot, the redstone dust remains powered?
Hmm... that's kind of a big bug if that's the case.

**Comment by lublak** [comment]
@dannydjdk yes. It keeps powered. I think the block not gives an update.

**Comment by dannydjdk** [comment]
I am able to reproduce this. It only applies to this specific scenario when a tiny solid block is on the edge of the panel and sending a signal outside. When the source goes away, the tiny block and the redstone dust continue to pick up each other's signal.
Should be fixed soon.

**Comment by dannydjdk** [comment]
Released with 1.16.5-1.5.1b
