### ISSUE TITLE
Consider Making Silicon Compound Recipe Shapeless

### ISSUE THREAD

**Issue by gigawhip** [dannydjdk/Tiny-Redstone#122]
It seems to make more sense, and in Create it would make the recipe use a mixer which makes a whole lot of sense for a pile of dust.

![image](https://user-images.githubusercontent.com/103098495/222949343-a41e6a84-59fe-46c3-aede-7831e08aab37.png)

**Comment by dannydjdk** [comment]
This does makes sense. Not sure why I went with a shaped recipe for this. Will be shapeless in the next update.
Thanks for the suggestion!
