### ISSUE TITLE
[Suggestion] Compatibility between create and tiny redstone++

### ISSUE THREAD

**Issue by Explosif3005** [dannydjdk/Tiny-Redstone#124]
I thinks, and i only thinks that it would be cool to hae an add-on that add create stuff in small version of themselfs (sorry for my relatively poor english). That would allow for compact desing. And i remember that Valkirian Skyes and the soon to be Create Aeronotics use and other dimension were they let the interactable block loaded so that they can continu to do stuff (for exemple furnace burning or redstone doing stuff...). Can you try to implement that as a compatibilty betwen create and you?

**Comment by dannydjdk** [comment]
Both mods use vanilla redstone, and therefore, they are compatible. As for copying their components into my own mod, I feel like that would just be stealing their ideas. I don't really want to do that.

Check out the [Tiny Gates](https://www.curseforge.com/minecraft/mc-mods/tiny-gates) and [Ranged Wireless Redstone](https://www.curseforge.com/minecraft/mc-mods/ranged-wireless-redstone) add-on mods. They probably have most of the functionality you are looking for. You can't get much more compact than that.

I don't really understand what you mean about the "other dimension" thing, but I think you might be looking for chunk loaders. There are many mods that have chunk loaders (like [Chicken Chunks](https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8)). I feel like chunk loading is outside of the scope of this mod.

**Comment by dannydjdk** [comment]
I think I understand what you're asking about Create Aeronautics. You want Tiny Redstone circuits to work on the moving contraptions, right? In that case, that is completely out of my hands. They would need to implement that on their end. If they implement it in a way that Block Entities can function on the contraptions, then Tiny Redstone will work. If Block Entities don't work, then Tiny Redstone won't work. There's nothing I can do about that.

**Comment by crafting-Aaron** [comment]
So this would be more on their end? They would have to use this https://github.com/dannydjdk/Tiny-Redstone/wiki/Creating-Add-On-Mods
So it makes more sense to make the request/suggestion to the Create mod. Especially with the complex components like the elevator detector blocks.

I am not too knowledgeable on making mods but could this article mean I could make my own add-on for compatibility or would this need to be an official add-on from their team?

**Comment by dannydjdk** [comment]
@crafting-Aaron It depends what you want to do. The API is for adding new Tiny Components. That is what you would use to create tiny versions of Create components. I'm fairly certain the Create developers would not be interested in doing that, but yes, you could do it if you want to learn the API. It wouldn't really need to be a Create add-on unless you wanted to hook into something on the Create end.

If you want Tiny Redstone circuits to work on moving contraptions, that would be on their end. Tiny Redstone circuits are just ticking block entities like furnaces, hoppers, Brewing Stands etc. So, there isn't anything special they would have to do to support Tiny Redstone. If they support block entities, Tiny Redstone circuits will work. If they don't, they won't. As far as I know, block entities do not work on Create contraptions, but they are expected to work with Create Aeronautics.
