### ISSUE TITLE
[bug] redstoneblock as input not works

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#14]
I hope it's okay if I try everything ^^"
![grafik](https://user-images.githubusercontent.com/44057030/111875205-e67e4000-8998-11eb-878a-c1c9c808f610.png)

**Comment by dannydjdk** [comment]
Please do! 🤩
Not sure how I missed this. :/

**Comment by dannydjdk** [comment]
Released with 1.16.5-1.5.1b

**Comment by dannydjdk** [comment]
@lublak keep this up, and I'll be able to move from beta to release this weekend! 😉
