### ISSUE TITLE
[feature request] Repeater GUI - sneak key or separate component

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#15]
To skip the gui https://github.com/dannydjdk/Tiny-Redstone/blob/master/src/main/java/com/dannyandson/tinyredstone/blocks/panelcells/Repeater.java#L344 und just go back to 1 tick.
Or the other way round, that the gui opens when sneaking.

**Comment by dannydjdk** [comment]
I too find it annoying that that GUI comes up on the 4th click. It feels unexpected and disruptive when you're just expecting it to go back to 1 tick.

I had a plan to add another component called something like "super tiny repeater". The existing tiny repeater would just act like a vanilla repeater, and the super repeater would always have the GUI. My justification for the added functionality is that you can't do hopper clocks. I don't ever expect to implement any container blocks like hoppers.

However, your sneaking idea is definitely a good alternative.

**Comment by lublak** [comment]
an extra itemHowever, an extra component is not a bad idea either. Maybe to make the recipe more expensive.

**Comment by dannydjdk** [comment]
Released in 1.16.5-1.5.2b
