### ISSUE TITLE
[bug] piston over two panels

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#16]
I just noticed. Whether this is really a bug ... I doubt it myself.
(i like the feature that you can expand your redstone panels 👍 )

But I noticed it anyway :)

If you place two panels it looks like this

![grafik](https://user-images.githubusercontent.com/44057030/111876998-817b1800-89a1-11eb-8c0d-d9f66a6d5b90.png)

if i remove the second panel
![grafik](https://user-images.githubusercontent.com/44057030/111877048-bbe4b500-89a1-11eb-85ff-5fe12b58c927.png)

=============

if i place only one panel:

![grafik](https://user-images.githubusercontent.com/44057030/111877072-d159df00-89a1-11eb-80d6-8f0b702f9378.png)

after placing a second panel:
![grafik](https://user-images.githubusercontent.com/44057030/111877079-dd45a100-89a1-11eb-9463-86aa63461b26.png)

**Comment by dannydjdk** [comment]
Ah. Pistons are only being notified of neighbor block redstone updates, not neighbor block changes affecting extendability.
