### ISSUE TITLE
[feature request] take redstone signal from any block

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#18]
![grafik](https://user-images.githubusercontent.com/44057030/111880001-31a04f00-89a9-11eb-89e7-27468344567e.png)
![grafik](https://user-images.githubusercontent.com/44057030/111880005-3c5ae400-89a9-11eb-8528-c401351d69a4.png)
![grafik](https://user-images.githubusercontent.com/44057030/111880018-4977d300-89a9-11eb-878a-cffb80c3b044.png)

**Comment by dannydjdk** [comment]
I need to change the way redstone dust reads weak signals. Vanilla redstone dust is a bit inconsistent. It does not read weak signals from most solid blocks, but it does read it from levers, tile entities, buttons, levers.
What I'm doing is basically whitelisting what it reads from. I may need to do the opposite of that.

FYI: A workaround is to use a Tiny Repeater at the edge of the block. It's only tiny redstone dust that behaves this way.
