### ISSUE TITLE
[feature request] render item in inventory

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#21]
Sometimes I don't know what's in my hand (panel).
I currently know one mod which has something like this:
https://github.com/ochotonida/some-assembly-required/blob/1.16/src/main/java/someassemblyrequired/client/SandwichItemRenderer.java

**Comment by dannydjdk** [comment]
I've been thinking about this. Steve's carts did something similar. It would be new ground for me, but it would be pretty amazing. In the meantime, I may do something similar to the blueprints where the tooltip shows a list of components contained within.

**Comment by dannydjdk** [comment]
![2021-03-21_12 50 45](https://user-images.githubusercontent.com/17087603/111915444-509fef00-8a44-11eb-89f3-ad34972fcc1a.png)
😀

**Comment by lublak** [comment]
@dannydjdk Oh hell jear. 
I love it

**Comment by dannydjdk** [comment]
lol. Strangely, the rendering part was relatively easy. I just has to loop through the NBT data, construct the objects for all the little cells and their render methods used for the block rendering. The hard part was figuring out how to get Minecraft to call that rendering script. The docs for that bit were not very complete.

**Comment by dannydjdk** [comment]
Released with 1.16.5-1.5.3b
