### ISSUE TITLE
[bug] colored panel placing

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#22]
When removing a colored panel and placing it, the panel loses its color.
~atfer placing a component it gets its color back.~
It is enough if you somehow interact with the panel. 
![grafik](https://user-images.githubusercontent.com/44057030/111886346-5ad2d680-89cd-11eb-9a1c-8f2c4208c3d8.png)
![grafik](https://user-images.githubusercontent.com/44057030/111886356-61614e00-89cd-11eb-9c0e-7f23766d0161.png)
![grafik](https://user-images.githubusercontent.com/44057030/111886415-98cffa80-89cd-11eb-8c3e-acc236b081bb.png)

**Comment by dannydjdk** [comment]
Released in 1.16.5-1.5.2b
