### ISSUE TITLE
[bug] rendering glitch piston if changes are made too quickly (over multiple panels)

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#38]
Only in rendering. If i place a block it syncs again
It is very difficult to fabricate.

Also, if changes are made too quickly in general, it looks very slippery.

![grafik](https://user-images.githubusercontent.com/44057030/113280425-8d8da080-92e4-11eb-8e25-5a0fe0522279.png)

**Comment by dannydjdk** [comment]
I did notice this. I need to come up with a way to tell that tile to sync to client. Now that the IPanelCells are kind of directly accessing cells in other panels, I need a way for them to tell the panel to sync.

**Comment by lublak** [comment]
performance + dirty vs bigger overhead
that's always a matter that has to be weighed up.
I think the tick performance should be as optimal as possible.
Maybe the onPlace method https://github.com/dannydjdk/Tiny-Redstone/issues/27. 
With a transfer value of the type PanelCellPos.

**Comment by dannydjdk** [comment]
Fixed in 1.16.5-1.6.0b
