### ISSUE TITLE
[feature request] alt (or sneaking)+scroll for manual rotation

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#39]
It's a real pain to place things correctly in vertical mode.

I'm working on it.

```
interface IScrollItem {
  boolean scroll();
}

if(item instaceof IScrollItem && ((IScrollItem) item).scroll()) event.setCanceled(true);
```

**Comment by dannydjdk** [comment]
I like this idea! I also found it to be a bit annoying. You have to place it at head level and then place a block nearby for facing components down. You do kind of get used to it after a while, but having a way to rotate would be nice. My other thought was that you could make circuits on a flat surface and then move them to the wall, but again, this would be better.

**Comment by dannydjdk** [comment]
Any thoughts on how persistently it will maintain the selected direction? My thought is that once you sneak scroll, the direction of the cell will lock into place until you look away from a panel, at which point it will reset to the default behavior.

**Comment by lublak** [comment]
I had in mind that it loses the rotation lock during the main hand item change.
Looking away can also be an option. I think it's time again for a new configuration option.

**Comment by dannydjdk** [comment]
Hmm.. not sure if I'd want a configuration option for this. I think it would be difficult to understand. The problem is that pack makers may have different preferences, and most users wouldn't understand why it's behaving differently than they expect in different packs.
