### ISSUE TITLE
[bug] difference between vanilla observer and tiny observer

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#40]
A very short and only one-time signal:

![grafik](https://user-images.githubusercontent.com/44057030/113283918-2faf8780-92e9-11eb-85b4-763c0c111397.png)

A little longer and two signals:

![grafik](https://user-images.githubusercontent.com/44057030/113284102-6eddd880-92e9-11eb-87f5-255153e23aed.png)

**Comment by dannydjdk** [comment]
Fixed in 1.16.5-1.6.0b
