### ISSUE TITLE
[bug] breaking and placing active panel

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#42]
panel remains active if you dismantle it in an active state and place it again.
![grafik](https://user-images.githubusercontent.com/44057030/113314109-3a2f4880-930c-11eb-9b76-034720734bec.png)

**Comment by dannydjdk** [comment]
Wait... I fixed this. And I also made those blocks translucent. Are you sure you have the latest?

**Comment by lublak** [comment]
Oh my mistake was the wrong Minecraft session.
I can't believe I didn't notice...
