### ISSUE TITLE
Tiny Common Logic Components

### ISSUE THREAD

**Issue by Pentasis** [dannydjdk/Tiny-Redstone#45]
You asked me to put this here from the curseforge comment section.
If/when you make an add-on perhaps you can consider adding components besides (n)and, (n)or and x(n)or, like:
- counters (set amount, increase/decrease on signal and reset on side)
- timer/pulse-generator (in ticks/seconds/minutes)
- sr-latch (and/or toggle-latch)
- raising/falling edge detectors
- on/off delays (again in ticks/seconds/minutes)

Again, thank you for this mod, it saves me loads of space and I love designing circuits with it.

**Comment by dannydjdk** [comment]
Thanks for the ideas! I will be considering all of these.

**Comment by dannydjdk** [comment]
Work in progress:
https://github.com/dannydjdk/Tiny-Gates
Currently in development for 1.17.1.

**Comment by dannydjdk** [comment]
Tiny Gates is ready for 1.17.1! Please check it out at https://www.curseforge.com/minecraft/mc-mods/tiny-gates
If you have any issues, ideas or suggestions for that mod, please use the Issues link for that mod.
