### ISSUE TITLE
Some Redstone Components are invisible when using "Fabulous" graphics

### ISSUE THREAD

**Issue by DarkShadow44** [dannydjdk/Tiny-Redstone#48]
Most prominently, redstone wire is affected. Using "Fast" or "Fancy" renders it properly.

**Comment by dannydjdk** [comment]
Confirmed. Thanks for reporting this!

Anything using RenderType.getTranslucent() is not rendering at all with Fabulous graphics.
This applies to redstone wire, bridge, glass blocks, placement preview ghost blocks and the crash overlay.

**Comment by dannydjdk** [comment]
Fix is available in 1.16.5-1.7.2b.

When using Fabulous graphics, all components now render as solid. This means that some things will actually look nicer in Fancy than Fabulous, but you will be able to see them now.

I'll be revisiting the translucency rendering in the future, but for now, I'm considering this issue resolved.
