### ISSUE TITLE
[bug] redstone on piston

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#50]
In vanilla, the redstone on pistons is destroyed when they are powered.

![grafik](https://user-images.githubusercontent.com/44057030/116463117-984b3f00-a86a-11eb-80cb-2410c242c243.png)

**Comment by dannydjdk** [comment]
Yes. I did list this (sort of) in the known issues in #8. Tiny redstone dust (along with Tiny Repeaters and Torches) always stays in place, even when the tiny block below it is removed.

Another consideration, I designed Tiny Pistons to not "pop" redstone dust in its path, but rather to just treat it as a non-pushable block. Maybe it's time to reconsider that decision as well.

**Comment by dannydjdk** [comment]
Perhaps another question to consider is this: is this vanilla behavior useful? If we choose to allow redstone to remain on top of an extended piston, will it break any vanilla redstone mechanics, or will it just add to the compactness potential of circuits without any undesired side affects?

**Comment by lublak** [comment]
I had read the list, but since it was a different variety, I thought: better make a note of it.
Maybe you can define methods with: `needBase():boolean;` and `needStaticBase():boolean` or something like that.
`needStaticBase`: pistons are bases but not static.

Because of redstone on pistons:
One possibility is that you can build a kind of fuse.
At the moment I don't know of any other advantage. Only that it's a certain limitation and that's just the way it is with vanilla.
I am not aware of any side effects.

**Comment by dannydjdk** [comment]
I decided to go with vanilla behavior here for consistency and for the reason you mentioned. In general, it's hard to predict how someone may end up using vanilla mechanics that don't seem to have a good use at first.
With that in mind, we will likely see an update in the near future allowing pistons to break redstone, repeaters, etc. in their path.

**Comment by dannydjdk** [comment]
Oh wait! I forgot to make the back of the piston safe for placement.
