### ISSUE TITLE
[Enhancement] Panel Free Placement

### ISSUE THREAD

**Issue by dannydjdk** [dannydjdk/Tiny-Redstone#53]
Right clicking a tiny component in the world where there is no existing Redstone Panel block would place that tiny component in the world. 

- Technically, an invisible Redstone Panel tile entity would automatically be placed in that block space allowing for placement of components in a full 8x8x8 area.
- Removing the last component will remove the tile entity.
- The block will always be horizontal facing (technically downward), but can input/output redstone in all 6 directions.
- Breaking the block with a pickaxe or by shift-right clicking with a wrench will drop a single block containing all the components within that block space (somewhat similar to C&B).
- Right clicking a blueprint in the world could place the circuit in world.
- Redstone Panels could still be used when desired and for placement in other orientations.

**Comment by lublak** [comment]
I've had the thought myself. But somehow I had mixed feelings. I still don't know why I have these mixed feelings xD

**Comment by dannydjdk** [comment]
I don't know why either, but I have had mixed feelings as well. I considered this idea when first designing the mod, but it seemed to make more sense to have a circuit board. Now that we're going 3d, the circuit board seems like an unnecessary restriction. Maybe people will finally stop comparing it to SCM! Mmm.... probably not. lol

One drawback to this idea that I can think of is the potential for confusion about block spaces. When a circuit spans multiple blocks, it won't be as obvious to the user where the block boundaries are. However, anyone who has worked with C&B will be accustomed to this idea, and the block boundaries will still be highlighted when looking at the block.

**Comment by lublak** [comment]
One thing that would also change would be the cover. It would then have to be a "cover block".
And hmmm there would even be a new idea. 
Camouflage cover blocks.

**Comment by lublak** [comment]
![grafik](https://user-images.githubusercontent.com/44057030/116795771-a3ef6d80-aad7-11eb-873a-0869e512e1e5.png)

**Comment by dannydjdk** [comment]
I had considered camouflage when I first made covers. It looked like it was going to take more time than I wanted to put into it, but it's probably time to revisit that. Even with the panels, 3d makes the current covers a bit insufficient looking. At the very least, they need to be full block now.

**Comment by dannydjdk** [comment]
Hmm.. did you post that image to the wrong issue?

**Comment by lublak** [comment]
@dannydjdk Well, the question is whether it is still an issue if it can be placed freely. Theoretically, the piston can then also push down into the tiny redstone structure below. xD

**Comment by dannydjdk** [comment]
Ah. Makes sense. With the panel, signals and pistons are not meant to pass through the panel, but they can go out to every other direction. Without the panel, yes, pistons will be able to push downward into the next block space if tiny redstone components exist there too. For now, the above image demonstrates a bug, but it has since been fixed.
