### ISSUE TITLE
[dev] The One Probe Override doesn't override redstone output

### ISSUE THREAD

**Issue by dannydjdk** [dannydjdk/Tiny-Redstone#59]
The One Probe is now showing component redstone outputs based on the side of the component being viewed. However, if the side of the component also corresponds to a side of the panel that is outputting redstone, The One Probe is displaying that redstone output too.

![2021-05-05_20 16 14](https://user-images.githubusercontent.com/17087603/117229338-7446ab00-ade0-11eb-9b29-2c70bb29583f.png)

How do we tell The One Probe not to display the panel's redstone output when we're looking at a component?

Any idea @lublak?

**Comment by lublak** [comment]
I had made a pull request for quite some time but unfortunately mcjty never looked at it:
https://github.com/McJtyMods/TheOneProbe/pull/453
I'm looking for a workaround.

**Comment by dannydjdk** [comment]
Since we can't rely on this being pulled by McJty, one idea is to add a sub-header at the end of the custom probe info labeled "Redstone Panel". That way, it will be clear that the redstone output displayed at the bottom pertains to the panel, not the component.

**Comment by lublak** [comment]
fixed in https://github.com/dannydjdk/Tiny-Redstone/pull/61

**Comment by dannydjdk** [comment]
Fixed in 1.16.5-1.8.0b
