### ISSUE TITLE
[bug] can't change redstone lamp color

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#63]
![grafik](https://user-images.githubusercontent.com/44057030/117556580-b71bb380-b06a-11eb-9af4-563f30251c05.png)

**Comment by dannydjdk** [comment]
When you right click on the lamp with a colorizer, is the GUI not appearing, or is the color not changing after selecting a color?

**Comment by lublak** [comment]
It's shows the GUI selector. But after selecting the color nothing changes.

**Comment by dannydjdk** [comment]
I'll take a look at this later tonight. My guess is that something in the Fabulous graphics fix broke this.

**Comment by dannydjdk** [comment]
Fixed in 1.16.5-1.8.0b
