### ISSUE TITLE
[bug] panel becomes invisible if base is not within field of view

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#66]
Panel becomes invisible when you look over it. (but only from a special angle, above)

![grafik](https://user-images.githubusercontent.com/44057030/118024149-a1ee9f80-b35e-11eb-9f41-794979a70bd8.png)
![grafik](https://user-images.githubusercontent.com/44057030/118024093-94391a00-b35e-11eb-90b1-c7e8e585af58.png)

**Comment by dannydjdk** [comment]
If the panel base is not within your field of view, the components do not render. I have attempted to fix this by changing the VoxelShape returned by getRenderShape. It did not fix the problem, so further research is needed.

**Comment by dannydjdk** [comment]
Fix released in version 1.16.5-1.8.3
