### ISSUE TITLE
[feature request] hide the redstone logic

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#7]
Alow the placer to hide the redstone logic. Could improve performance.

Already on your to-do list

**Comment by dannydjdk** [comment]
My plan is to add a "cover" that you can craft and right click on a panel to install. I want it to look like an electronic box or console.

I'm playing around with the idea of having 2 of them, one that allows light output and another that doesn't. The light output box might look a little like an opaque light fixture.

**Comment by lublak** [comment]
Cool idea to make it as an extra component. I like the idea.
Also with the two different.

**Comment by dannydjdk** [comment]
Fixed in 1.16.5-1.6.0b
