### ISSUE TITLE
Tiny Comparators not working like normal ones

### ISSUE THREAD

**Issue by tobi-blackscale** [dannydjdk/Tiny-Redstone#71]
Regular Comparator (Normal mode)
Out = Rear x (Left <= Rear and Right <= Rear)

Tiny Comparator
Out = Rear x (Left < Rear and Right < Rear)

In subtracting mode both work the same.

Version:
tinyredstone-1.16.5-1.8.2.jar

**Comment by dannydjdk** [comment]
Ooh! Thanks for catching that! Should be fixed in the next update.

**Comment by dannydjdk** [comment]
Fix released in version 1.16.5-1.8.3
