### ISSUE TITLE
Recipe tiny note block is missing

### ISSUE THREAD

**Issue by csiemann** [dannydjdk/Tiny-Redstone#82]
I was playing all the mods 6 and saw that the tiny note block was out of a recipe, so I went to see if something was wrong and it really wasn't there, take a look at this recipe that doesn't have.

**Comment by dannydjdk** [comment]
Thank you for reporting this! I can't believe I missed that. 😑

**Comment by dannydjdk** [comment]
Fixed in versions 1.17.1-2.2.7 and 1.16.5-1.10.5.
