### ISSUE TITLE
Option for smaller plates

### ISSUE THREAD

**Issue by aburone** [dannydjdk/Tiny-Redstone#83]
An option to make the plate visually only as big as the circuit itself would be rad. So these "boxes" would be way smaller and more visually pleasing.

Look at this image to see what I mean
https://imgur.com/gallery/ibJsfoD
I'm just transmitting the signal from a daylight sensor to turn on the lamps at night, If the plate had the size of only the components, it'll be almost invisible

**Comment by lublak** [comment]
If the plate itself is only as big as the circuit itself then you will have a very big problem, especially if you place it vertically.
How do you want to place other components?
Here is an alternative solution that does not work vertically.
https://github.com/dannydjdk/Tiny-Redstone/issues/53

**Comment by aburone** [comment]
I don't say to make the plate -actually- smaller, just the empty areas to be invisible.

Start with a normal plate and, when I break it to move it, having the option to "trim" it.
The collision box remaining the same, just with invisible areas, where there are no components

**Comment by dannydjdk** [comment]
One potential option could be a cover that, when placed, trims it down to a box just covering the components. Then, you'll have the full panel when you're working with the circuit but a small box when you're not.

Also, don't forget you can dye the boxes. It might stand out less if it matches the surrounding blocks. Also also, camouflage covers (#69) may be coming soon.

**Comment by aburone** [comment]
> 
> 
> One potential option could be a cover that, when placed, trims it down to a box just covering the components. Then, you'll have the full panel when you're working with the circuit but a small box when you're not.
> 

Oh. I like that option very much.


I tried doing this (the lightning of the floors) with Redstone Control II because the microblocks would be perfect for this, but the wireless transmitter are 1-1 not 1-many :(

**Comment by dannydjdk** [comment]
"Trimming Panel Cover" released in 1.17.1-2.4.0 and 1.16.5-1.11.1.
