### ISSUE TITLE
[Feature request] A config option to disable tiny redstone in world

### ISSUE THREAD

**Issue by arainflake** [dannydjdk/Tiny-Redstone#89]
Onlly allow tiny redstone to be placed on its panels; toggleable via configs

**Comment by dannydjdk** [comment]
Thanks for the suggestion! This will be available in the next update all 3 version.

**Comment by dannydjdk** [comment]
Feature released in latest versions for all 3 MC versions.

Setting "allow_world_placement" to false will restrict placement of components (and blueprints) to Redstone Panels. It will not affect any existing components already placed though.
