### ISSUE TITLE
[feature request] locked repeater

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#9]
Allow the repeater to be locked if it powered from the side.

**Comment by dannydjdk** [comment]
Is there a vanilla equivalent to this feature that I'm not thinking of?

**Comment by lublak** [comment]
Of course! Look under https://minecraft.gamepedia.com/Redstone_Repeater signal locking

**Comment by dannydjdk** [comment]
Ah. I feel silly now. lol. So, it should lock on side input from a repeater or comparator.

**Comment by lublak** [comment]
Why silly? You make a nice mod and did not have one thing on the screen.
Definitely yes. This is how the luring of a repeater works.
A very important functionality, especially if you work in the 2d area.

**Comment by dannydjdk** [comment]
Released

**Comment by lublak** [comment]
I love it

![grafik](https://user-images.githubusercontent.com/44057030/111518014-f528e500-8755-11eb-8ef1-c5a422cdc08d.png)
 T-Latch Circuit
