### ISSUE TITLE
[1.18.1 v3.1.0] Redstone output not updated when placing circuit

### ISSUE THREAD

**Issue by lincore81** [dannydjdk/Tiny-Redstone#90]
Hi. Thank you for this great mod.

I built a simple AND gate and noticed the circuit does not update the outputting side when placed. It works properly again when I force the circuit to update (by changing the input or circuit).

![Screenshot 2022-01-09 104400](https://user-images.githubusercontent.com/1869090/148677213-5cecb69a-7f70-46b7-9f16-df83a62b8ade.png)

**Comment by dannydjdk** [comment]
I was able to reproduce this and fix it in the dev environment, so expect a fix in the next release.

Thanks for the report!

**Comment by dannydjdk** [comment]
Fix released in latest versions for all 3 MC versions.
