### ISSUE TITLE
[1.16] Kicks player from server when TinyBlockItem.getName is called

### ISSUE THREAD

**Issue by jeremiahwinsley** [dannydjdk/Tiny-Redstone#97]
https://gist.github.com/radiomike/744fa87fbb9e97cc38bd564053b25e1a

This method calls `ITextComponent.nullToEmpty` which is only available client-side: https://github.com/dannydjdk/Tiny-Redstone/blob/0d4b4b7e847a0dd77f97dc8c81c9263d4c4b104b/src/main/java/com/dannyandson/tinyredstone/items/TinyBlockItem.java#L39

**Comment by dannydjdk** [comment]
Thanks for reporting this! It looks like Mahou Sukai is grabbing the item name text component on the server side. It's not something I would have expected, and thus it didn't come up in testing. However, it should be easy to fix on my end.

Note: This is only an issue in 1.16. Component.nullToEmpty is available server-side in 1.17+. Apparently, Mojang also stumbled upon a use case for text components server side.

**Comment by dannydjdk** [comment]
Fix released in 1.13.2

**Comment by jeremiahwinsley** [comment]
@dannydjdk Seems like the same issue is present on PanelCoverItem as well.

**Comment by dannydjdk** [comment]
> @dannydjdk Seems like the same issue is present on PanelCoverItem as well.

Yes. This should be fixed in the latest release as well.
