### ISSUE TITLE
Blocks not getting updated after removing circuit

### ISSUE THREAD

**Issue by Pentasis** [dannydjdk/Tiny-Redstone#98]
I am uncertain if this is a bug, or even if it is related to your mod. But I noticed "residual" redstone signals around places I had previously placed circuits. Then yesterday I came across the situation below which visualized it.
![Screenshot (70)](https://user-images.githubusercontent.com/7046024/154656746-0d5484d0-3130-4685-88ed-a1d56caf2278.png)
![Screenshot (71)](https://user-images.githubusercontent.com/7046024/154656763-ed761019-26d4-4a4e-abae-963824d6c18c.png)
![Screenshot (72)](https://user-images.githubusercontent.com/7046024/154656777-05bf1252-d131-43e9-98af-5fc8769bc3e7.png)
i.e. after removing the circuit the lamps around the previously powered one don't update.
Apologies if posted in the wrong place.

**Comment by dannydjdk** [comment]
Thanks for reporting this! I'd like to call this a vanilla bug, but if you do the same thing with vanilla redstone, it works as expected. It's just a vanilla oddity that "quasi-connected" neighbors blocks don't get updated when a block's redstone signal changes. Somehow, I need to force each neighbor to update its neighbors when the block entity is broken.

**Comment by dannydjdk** [comment]
Now fixed in all MC versions, including the new 1.19 version.
